name: CI
on:
  push:
    branches-ignore:
      - 'generated'
      - 'codegen/**'
      - 'integrated/**'
      - 'stl-preview-head/**'
      - 'stl-preview-base/**'
  pull_request:
    branches-ignore:
      - 'stl-preview-head/**'
      - 'stl-preview-base/**'

env:
  GOPRIVATE: github.com/stainless-sdks/spotted-go

jobs:
  lint:
    runs-on: ${{ github.repository == 'stainless-sdks/spotted-terraform' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go
        with:
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Run lints
        run: ./scripts/lint

  test:
    runs-on: ${{ github.repository == 'stainless-sdks/spotted-terraform' && 'depot-ubuntu-24.04' || 'ubuntu-latest' }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go
        with:
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Run tests
        run: ./scripts/test